package main

var tzMap = map[string]string{
	"(GMT-12:00) International Date Line West":         "Etc/GMT+12",
	"(GMT-11:00) Coordinated Universal Time-11":        "Etc/GMT+11",
	"(GMT-11:00) Midway":                               "Pacific/Midway",
	"(GMT-11:00) Niue":                                 "Pacific/Niue",
	"(GMT-11:00) Pago_Pago":                            "Pacific/Pago_Pago",
	"(GMT-11:00) Samoa":                                "Pacific/Samoa",
	"(GMT-10:00) Adak":                                 "America/Adak",
	"(GMT-10:00) Rarotonga":                            "Pacific/Rarotonga",
	"(GMT-10:00) Tahiti":                               "Pacific/Tahiti",
	"(GMT-10:00) Hawaii":                               "Pacific/Honolulu",
	"(GMT-09:30) Marquesas\n Islands":                  "Pacific/Marquesas",
	"(GMT-09:00) Alaska":                               "America/Anchorage",
	"(GMT-09:00) Gambier":                              "Pacific/Gambier",
	"(GMT-08:00) Juneau":                               "America/Juneau",
	"(GMT-08:00) Nome":                                 "America/Nome",
	"(GMT-08:00) Metlakatla":                           "America/Metlakatla",
	"(GMT-08:00) Sitka":                                "America/Sitka",
	"(GMT-08:00) Yakutat":                              "America/Yakutat",
	"(GMT-08:00) Baja California":                      "America/Tijuana",
	"(GMT-08:00) Pacific Time (US & Canada)":           "America/Los_Angeles",
	"(GMT-08:00) Pitcairn":                             "Pacific/Pitcairn",
	"(GMT-07:00) Creston":                              "America/Creston",
	"(GMT-07:00) Chihuahua, Mazatlan":                  "America/Chihuahua",
	"(GMT-07:00) Dawson":                               "America/Dawson",
	"(GMT-07:00) Dawson Creek":                         "America/Dawson_Creek",
	"(GMT-07:00) Mountain Time (US & Canada)":          "America/Denver",
	"(GMT-07:00) Ensenada":                             "America/Ensenada",
	"(GMT-07:00) Fort Nelson":                          "America/Fort_Nelson",
	"(GMT-07:00) Hermosillo":                           "America/Hermosillo",
	"(GMT-07:00) Vancouver":                            "America/Vancouver",
	"(GMT-07:00) Whitehorse":                           "America/Whitehorse",
	"(GMT-07:00) Arizona":                              "America/Phoenix",
	"(GMT-06:00) Bahia Banderas":                       "America/Bahia_Banderas",
	"(GMT-06:00) Belize":                               "America/Belize",
	"(GMT-06:00) Boise":                                "America/Boise",
	"(GMT-06:00) Costa Rica":                           "America/Costa_Rica",
	"(GMT-06:00) Central Time (US & Canada)":           "America/Chicago",
	"(GMT-06:00) Edmonton":                             "America/Edmonton",
	"(GMT-06:00) El Salvador":                          "America/El_Salvador",
	"(GMT-06:00) Central America":                      "America/Guatemala",
	"(GMT-06:00) Managua":                              "America/Managua",
	"(GMT-06:00) Mazatlan":                             "America/Mazatlan",
	"(GMT-06:00) Ojinaga":                              "America/Ojinaga",
	"(GMT-06:00) Swift Current":                        "America/Swift_Current",
	"(GMT-06:00) Tegucigalpa":                          "America/Tegucigalpa",
	"(GMT-06:00) Guadalajara, Mexico City, Monterrey":  "America/Mexico_City",
	"(GMT-06:00) Saskatchewan":                         "America/Regina",
	"(GMT-06:00) Galapagos":                            "Pacific/Galapagos",
	"(GMT-05:00) Atikokan":                             "America/Atikokan",
	"(GMT-05:00) Bogota, Lima, Quito":                  "America/Bogota",
	"(GMT-05:00) Cancun":                               "America/Cancun",
	"(GMT-05:00) Cayman":                               "America/Cayman",
	"(GMT-05:00) Coral Harbour":                        "America/Coral_Harbour",
	"(GMT-05:00) Eirunepe":                             "America/Eirunepe",
	"(GMT-05:00) Guayaquil":                            "America/Guayaquil",
	"(GMT-05:00) Indiana (East)":                       "America/Indianapolis",
	"(GMT-05:00) Jamaica":                              "America/Jamaica",
	"(GMT-05:00) Lima":                                 "America/Lima",
	"(GMT-05:00) Matamoros":                            "America/Matamoros",
	"(GMT-05:00) Menominee":                            "America/Menominee",
	"(GMT-05:00) Merida":                               "America/Merida",
	"(GMT-05:00) Monterrey":                            "America/Monterrey",
	"(GMT-05:00) Nipigon":                              "America/Nipigon",
	"(GMT-05:00) Panama":                               "America/Panama",
	"(GMT-05:00) Rainy River":                          "America/Rainy_River",
	"(GMT-05:00) Rio Branco":                           "America/Rio_Branco",
	"(GMT-05:00) Thunder Bay":                          "America/Thunder_Bay",
	"(GMT-05:00) Winnipeg":                             "America/Winnipeg",
	"(GMT-05:00) Eastern Time (US & Canada)":           "America/New_York",
	"(GMT-05:00) Easter":                               "Pacific/Easter",
	"(GMT-04:30) Caracas":                              "America/Caracas",
	"(GMT-04:00) Anguilla":                             "America/Anguilla",
	"(GMT-04:00) Antigua":                              "America/Antigua",
	"(GMT-04:00) Aruba":                                "America/Aruba",
	"(GMT-04:00) Asuncion":                             "America/Asuncion",
	"(GMT-04:00) Barbados":                             "America/Barbados",
	"(GMT-04:00) Boa Vista":                            "America/Boa_Vista",
	"(GMT-04:00) Campo Grande":                         "America/Campo_Grande",
	"(GMT-04:00) Curacao":                              "America/Curacao",
	"(GMT-04:00) Cuiaba":                               "America/Cuiaba",
	"(GMT-04:00) Detroit":                              "America/Detroit",
	"(GMT-04:00) Dominica":                             "America/Dominica",
	"(GMT-04:00) Grand Turk":                           "America/Grand_Turk",
	"(GMT-04:00) Grenada":                              "America/Grenada",
	"(GMT-04:00) Guadeloupe":                           "America/Guadeloupe",
	"(GMT-04:00) Guyana":                               "America/Guyana",
	"(GMT-04:00) Atlantic Time (Canada)":               "America/Halifax",
	"(GMT-04:00) Havana":                               "America/Havana",
	"(GMT-04:00) Georgetown, La Paz, Manaus, San Juan": "America/La_Paz",
	"(GMT-04:00) Manaus":                               "America/Manaus",
	"(GMT-04:00) Martinique":                           "America/Martinique",
	"(GMT-04:00) Montreal":                             "America/Montreal",
	"(GMT-04:00) Montserrat":                           "America/Montserrat",
	"(GMT-04:00) Nassau":                               "America/Nassau",
	"(GMT-04:00) Port of Spain":                        "America/Port_of_Spain",
	"(GMT-04:00) Porto Velho":                          "America/Porto_Velho",
	"(GMT-04:00) Puerto Rico":                          "America/Puerto_Rico",
	"(GMT-04:00) Santo Domingo":                        "America/Santo_Domingo",
	"(GMT-04:00) St. Kitts":                            "America/St_Kitts",
	"(GMT-04:00) St. Lucia":                            "America/St_Lucia",
	"(GMT-04:00) St. Thomas":                           "America/St_Thomas",
	"(GMT-04:00) St. Vincent":                          "America/St_Vincent",
	"(GMT-04:00) Toronto":                              "America/Toronto",
	"(GMT-04:00) Tortola":                              "America/Tortola",
	"(GMT-04:00) Santiago":                             "America/Santiago",
	"(GMT-03:30) Newfoundland":                         "America/St_Johns",
	"(GMT-03:00) Araguaina":                            "America/Araguaina",
	"(GMT-03:00) Bahia":                                "America/Bahia",
	"(GMT-03:00) Belem":                                "America/Belem",
	"(GMT-03:00) Buenos Aires":                         "America/Buenos_Aires",
	"(GMT-03:00) Cayenne,\n Fortaleza":                 "America/Cayenne",
	"(GMT-03:00) Fortaleza":                            "America/Fortaleza",
	"(GMT-03:00) Glace Bay":                            "America/Glace_Bay",
	"(GMT-03:00) Goose Bay":                            "America/Goose_Bay",
	"(GMT-03:00) Greenland":                            "America/Godthab",
	"(GMT-03:00) Maceio":                               "America/Maceio",
	"(GMT-03:00) Moncton":                              "America/Moncton",
	"(GMT-03:00) Paramaribo":                           "America/Paramaribo",
	"(GMT-03:00) Punta Arenas":                         "America/Punta_Arenas",
	"(GMT-03:00) Recife":                               "America/Recife",
	"(GMT-03:00) Rosario":                              "America/Rosario",
	"(GMT-03:00) Santarem":                             "America/Santarem",
	"(GMT-03:00) Thule":                                "America/Thule",
	"(GMT-03:00) Montevideo":                           "America/Montevideo",
	"(GMT-03:00) Brasilia":                             "America/Sao_Paulo",
	"(GMT-03:00) Rothera":                              "Antarctica/Rothera",
	"(GMT-03:00) Bermuda":                              "Atlantic/Bermuda",
	"(GMT-03:00) Stanley":                              "Atlantic/Stanley",
	"(GMT-02:00) Miquelon":                             "America/Miquelon",
	"(GMT-02:00) Noronha":                              "America/Noronha",
	"(GMT-02:00) South Georgia":                        "Atlantic/South_Georgia",
	"(GMT-02:00) Coordinated Universal Time-02":        "Etc/GMT+2",
	"(GMT-01:00) Azores":                               "Atlantic/Azores",
	"(GMT-01:00) Cape Verde":                           "Atlantic/Cape_Verde",
	"(GMT+00:00) Default":                              "UTC",
	"(GMT+00:00) Danmarkshavn":                         "America/Danmarkshavn",
	"(GMT+00:00) Scoresbysund":                         "America/Scoresbysund",
	"(GMT+00:00) Accra":                                "Africa/Accra",
	"(GMT+00:00) Abidjan":                              "Africa/Abidjan",
	"(GMT+00:00) Bamako":                               "Africa/Bamako",
	"(GMT+00:00) Banjul":                               "Africa/Banjul",
	"(GMT+00:00) Bissau":                               "Africa/Bissau",
	"(GMT+00:00) Conakry":                              "Africa/Conakry",
	"(GMT+00:00) Dakar":                                "Africa/Dakar",
	"(GMT+00:00) El Aaiun":                             "Africa/El_Aaiun",
	"(GMT+00:00) Freetown":                             "Africa/Freetown",
	"(GMT+00:00) Lome":                                 "Africa/Lome",
	"(GMT+00:00) Monrovia":                             "Africa/Monrovia",
	"(GMT+00:00) Nouakchott":                           "Africa/Nouakchott",
	"(GMT+00:00) Ouagadougou":                          "Africa/Ouagadougou",
	"(GMT+00:00) Sao Tome":                             "Africa/Sao_Tome",
	"(GMT+00:00) Timbuktu":                             "Africa/Timbuktu",
	"(GMT+00:00) Troll":                                "Antarctica/Troll",
	"(GMT+00:00) St. Helena":                           "Atlantic/St_Helena",
	"(GMT+00:00) Monrovia, Reykjavik":                  "Atlantic/Reykjavik",
	"(GMT+00:00) Greenwich Mean Time, Dublin, Edinburgh, Lisbon, London": "Europe/London",
	"(GMT+01:00) Bangui":              "Africa/Bangui",
	"(GMT+01:00) Casablanca":          "Africa/Casablanca",
	"(GMT+01:00) Algiers":             "Africa/Algiers",
	"(GMT+01:00) Brazzaville":         "Africa/Brazzaville",
	"(GMT+01:00) Douala":              "Africa/Douala",
	"(GMT+01:00) Kinshasa":            "Africa/Kinshasa",
	"(GMT+01:00) Libreville":          "Africa/Libreville",
	"(GMT+01:00) Luanda":              "Africa/Luanda",
	"(GMT+01:00) Malabo":              "Africa/Malabo",
	"(GMT+01:00) Ndjamena":            "Africa/Ndjamena",
	"(GMT+01:00) Niamey":              "Africa/Niamey",
	"(GMT+01:00) Tunis":               "Africa/Tunis",
	"(GMT+01:00) West Central Africa": "Africa/Lagos",
	"(GMT+01:00) Canary":              "Atlantic/Canary",
	"(GMT+01:00) Faroe":               "Atlantic/Faroe",
	"(GMT+01:00) Madeira":             "Atlantic/Madeira",
	"(GMT+01:00) Belfast":             "Europe/Belfast",
	"(GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna":  "Europe/Berlin",
	"(GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague": "Europe/Budapest",
	"(GMT+01:00) Dublin":                              "Europe/Dublin",
	"(GMT+01:00) Guernsey":                            "Europe/Guernsey",
	"(GMT+01:00) Isle of Man":                         "Europe/Isle_of_Man",
	"(GMT+01:00) Jersey":                              "Europe/Jersey",
	"(GMT+01:00) Lisbon":                              "Europe/Lisbon",
	"(GMT+01:00) Brussels, Copenhagen, Madrid, Paris": "Europe/Paris",
	"(GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb":    "Europe/Warsaw",
	"(GMT+02:00) Blantyre":                            "Africa/Blantyre",
	"(GMT+02:00) Bujumbura":                           "Africa/Bujumbura",
	"(GMT+02:00) Cairo":                               "Africa/Cairo",
	"(GMT+02:00) Ceuta":                               "Africa/Ceuta",
	"(GMT+02:00) Johannesburg":                        "Africa/Johannesburg",
	"(GMT+02:00) Gaborone":                            "Africa/Gaborone",
	"(GMT+02:00) Harare":                              "Africa/Harare",
	"(GMT+02:00) Khartoum":                            "Africa/Khartoum",
	"(GMT+02:00) Kigali":                              "Africa/Kigali",
	"(GMT+02:00) Lubumbashi":                          "Africa/Lubumbashi",
	"(GMT+02:00) Lusaka":                              "Africa/Lusaka",
	"(GMT+02:00) Maputo":                              "Africa/Maputo",
	"(GMT+02:00) Maseru":                              "Africa/Maseru",
	"(GMT+02:00) Mbabane":                             "Africa/Mbabane",
	"(GMT+02:00) Tripoli":                             "Africa/Tripoli",
	"(GMT+02:00) Windhoek":                            "Africa/Windhoek",
	"(GMT+02:00) Amman":                               "Asia/Amman",
	"(GMT+02:00) Beirut":                              "Asia/Beirut",
	"(GMT+02:00) Damascus":                            "Asia/Damascus",
	"(GMT+02:00) Jerusalem":                           "Asia/Jerusalem",
	"(GMT+02:00) Amsterdam":                           "Europe/Amsterdam",
	"(GMT+02:00) Andorra":                             "Europe/Andorra",
	"(GMT+02:00) Belgrade":                            "Europe/Belgrade",
	"(GMT+02:00) Brussels":                            "Europe/Brussels",
	"(GMT+02:00) Copenhagen":                          "Europe/Copenhagen",
	"(GMT+02:00) Gibraltar":                           "Europe/Gibraltar",
	"(GMT+02:00) Athens, Bucharest, Istanbul":         "Europe/Istanbul",
	"(GMT+02:00) Kaliningrad":                         "Europe/Kaliningrad",
	"(GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius": "Europe/Kiev",
	"(GMT+02:00) Ljubljana":                             "Europe/Ljubljana",
	"(GMT+02:00) Luxembourg":                            "Europe/Luxembourg",
	"(GMT+02:00) Madrid":                                "Europe/Madrid",
	"(GMT+02:00) Malta":                                 "Europe/Malta",
	"(GMT+02:00) Monaco":                                "Europe/Monaco",
	"(GMT+02:00) Minsk":                                 "Europe/Minsk",
	"(GMT+02:00) Oslo":                                  "Europe/Oslo",
	"(GMT+02:00) Prague":                                "Europe/Prague",
	"(GMT+02:00) Rome":                                  "Europe/Rome",
	"(GMT+02:00) Sarajevo":                              "Europe/Sarajevo",
	"(GMT+02:00) Skopje":                                "Europe/Skopje",
	"(GMT+02:00) Stockholm":                             "Europe/Stockholm",
	"(GMT+02:00) Tirane":                                "Europe/Tirane",
	"(GMT+02:00) Vaduz":                                 "Europe/Vaduz",
	"(GMT+02:00) Vienna":                                "Europe/Vienna",
	"(GMT+02:00) Zagreb":                                "Europe/Zagreb",
	"(GMT+02:00) Zurich":                                "Europe/Zurich",
	"(GMT+03:00) Addis Ababa":                           "Africa/Addis_Ababa",
	"(GMT+03:00) Asmara":                                "Africa/Asmara",
	"(GMT+03:00) Dar es Salaam":                         "Africa/Dar_es_Salaam",
	"(GMT+03:00) Djibouti":                              "Africa/Djibouti",
	"(GMT+03:00) Juba":                                  "Africa/Juba",
	"(GMT+03:00) Kampala":                               "Africa/Kampala",
	"(GMT+03:00) Mogadishu":                             "Africa/Mogadishu",
	"(GMT+03:00) Nairobi":                               "Africa/Nairobi",
	"(GMT+03:00) Aden":                                  "Asia/Aden",
	"(GMT+03:00) Bahrain":                               "Asia/Bahrain",
	"(GMT+03:00) Baghdad":                               "Asia/Baghdad",
	"(GMT+03:00) Famagusta":                             "Asia/Famagusta",
	"(GMT+03:00) Gaza":                                  "Asia/Gaza",
	"(GMT+03:00) Hebron":                                "Asia/Hebron",
	"(GMT+03:00) Kuwait":                                "Asia/Kuwait",
	"(GMT+03:00) Nicosia":                               "Asia/Nicosia",
	"(GMT+03:00) Qatar":                                 "Asia/Qatar",
	"(GMT+03:00) Tel Aviv":                              "Asia/Tel_Aviv",
	"(GMT+03:00) Kuwait, Riyadh":                        "Asia/Riyadh",
	"(GMT+03:00) Athens":                                "Europe/Athens",
	"(GMT+03:00) Bucharest":                             "Europe/Bucharest",
	"(GMT+03:00) Chisinau":                              "Europe/Chisinau",
	"(GMT+03:00) Helsinki":                              "Europe/Helsinki",
	"(GMT+03:00) Kirov":                                 "Europe/Kirov",
	"(GMT+03:00) Moscow, St. Petersburg, Volgograd":     "Europe/Moscow",
	"(GMT+03:00) Riga":                                  "Europe/Riga",
	"(GMT+03:00) Simferopol":                            "Europe/Simferopol",
	"(GMT+03:00) Sofia":                                 "Europe/Sofia",
	"(GMT+03:00) Tallinn":                               "Europe/Tallinn",
	"(GMT+03:00) Tiraspol":                              "Europe/Tiraspol",
	"(GMT+03:00) Uzhgorod":                              "Europe/Uzhgorod",
	"(GMT+03:00) Vilnius":                               "Europe/Vilnius",
	"(GMT+03:00) Volgograd":                             "Europe/Volgograd",
	"(GMT+03:00) Zaporozhye":                            "Europe/Zaporozhye",
	"(GMT+03:00) Antananarivo":                          "Indian/Antananarivo",
	"(GMT+03:00) Comoro":                                "Indian/Comoro",
	"(GMT+03:00) Mayotte":                               "Indian/Mayotte",
	"(GMT+03:30) Tehran":                                "Asia/Tehran",
	"(GMT+04:00) Baku":                                  "Asia/Baku",
	"(GMT+04:00) Muscat":                                "Asia/Muscat",
	"(GMT+04:00) Abu Dhabi, Muscat":                     "Asia/Dubai",
	"(GMT+04:00) Tbilisi":                               "Asia/Tbilisi",
	"(GMT+04:00) Yerevan":                               "Asia/Yerevan",
	"(GMT+04:00) Astrakhan":                             "Europe/Astrakhan",
	"(GMT+04:00) Samara":                                "Europe/Samara",
	"(GMT+04:00) Saratov":                               "Europe/Saratov",
	"(GMT+04:00) Ulyanovsk":                             "Europe/Ulyanovsk",
	"(GMT+04:00) Mahe":                                  "Indian/Mahe",
	"(GMT+04:00) Port Louis":                            "Indian/Mauritius",
	"(GMT+04:00) Reunion":                               "Indian/Reunion",
	"(GMT+04:30) Kabul":                                 "Asia/Kabul",
	"(GMT+05:00) Mawson":                                "Antarctica/Mawson",
	"(GMT+05:00) Aqtau":                                 "Asia/Aqtau",
	"(GMT+05:00) Aqtobe":                                "Asia/Aqtobe",
	"(GMT+05:00) Ashgabat":                              "Asia/Ashgabat",
	"(GMT+05:00) Atyrau":                                "Asia/Atyrau",
	"(GMT+05:00) Dushanbe":                              "Asia/Dushanbe",
	"(GMT+05:00) Oral":                                  "Asia/Oral",
	"(GMT+05:00) Samarkand":                             "Asia/Samarkand",
	"(GMT+05:00) Islamabad, Karachi":                    "Asia/Karachi",
	"(GMT+05:00) Tashkent":                              "Asia/Tashkent",
	"(GMT+05:00) Yekaterinburg":                         "Asia/Yekaterinburg",
	"(GMT+05:00) Maldives":                              "Indian/Maldives",
	"(GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi":   "Asia/Calcutta",
	"(GMT+05:30) Sri Jayawardenepura":                   "Asia/Colombo",
	"(GMT+05:30) Kolkata":                               "Asia/Kolkata",
	"(GMT+05:45) Kathmandu":                             "Asia/Kathmandu",
	"(GMT+06:00) Astana":                                "Asia/Almaty",
	"(GMT+06:00) Bishkek":                               "Asia/Bishkek",
	"(GMT+06:00) Kashgar":                               "Asia/Kashgar",
	"(GMT+06:00) Omsk":                                  "Asia/Omsk",
	"(GMT+06:00) Qyzylorda":                             "Asia/Qyzylorda",
	"(GMT+06:00) Thimphu":                               "Asia/Thimphu",
	"(GMT+06:00) Urumqi":                                "Asia/Urumqi",
	"(GMT+06:00) Dhaka":                                 "Asia/Dhaka",
	"(GMT+06:00) Novosibirsk":                           "Asia/Novosibirsk",
	"(GMT+06:00) Chagos":                                "Indian/Chagos",
	"(GMT+06:30) Yangon":                                "Asia/Yangon",
	"(GMT+06:30) Yangon (Rangoon)":                      "Asia/Rangoon",
	"(GMT+06:30) Cocos":                                 "Indian/Cocos",
	"(GMT+07:00) Davis":                                 "Antarctica/Davis",
	"(GMT+07:00) Barnaul":                               "Asia/Barnaul",
	"(GMT+07:00) Bangkok, Hanoi, Jakarta":               "Asia/Bangkok",
	"(GMT+07:00) Ho Chi Minh":                           "Asia/Ho_Chi_Minh",
	"(GMT+07:00) Hovd":                                  "Asia/Hovd",
	"(GMT+07:00) Jakarta":                               "Asia/Jakarta",
	"(GMT+07:00) Novokuznetsk":                          "Asia/Novokuznetsk",
	"(GMT+07:00) Phnom Penh":                            "Asia/Phnom_Penh",
	"(GMT+07:00) Pontianak":                             "Asia/Pontianak",
	"(GMT+07:00) Tomsk":                                 "Asia/Tomsk",
	"(GMT+07:00) Vientiane":                             "Asia/Vientiane",
	"(GMT+07:00) Krasnoyarsk":                           "Asia/Krasnoyarsk",
	"(GMT+07:00) Christmas":                             "Indian/Christmas",
	"(GMT+08:00) Casey":                                 "Antarctica/Casey",
	"(GMT+08:00) Brunei":                                "Asia/Brunei",
	"(GMT+08:00) Choibalsan":                            "Asia/Choibalsan",
	"(GMT+08:00) Chongqing":                             "Asia/Chongqing",
	"(GMT+08:00) Harbin":                                "Asia/Harbin",
	"(GMT+08:00) Hong Kong":                             "Asia/Hong_Kong",
	"(GMT+08:00) Kuala Lumpur":                          "Asia/Kuala_Lumpur",
	"(GMT+08:00) Kuching":                               "Asia/Kuching",
	"(GMT+08:00) Macau":                                 "Asia/Macau",
	"(GMT+08:00) Makassar":                              "Asia/Makassar",
	"(GMT+08:00) Manila":                                "Asia/Manila",
	"(GMT+08:00) Irkutsk":                               "Asia/Irkutsk",
	"(GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi": "Asia/Shanghai",
	"(GMT+08:00) Kuala Lumpur, Singapore":               "Asia/Singapore",
	"(GMT+08:00) Taipei":                                "Asia/Taipei",
	"(GMT+08:00) Ulaanbaatar":                           "Asia/Ulaanbaatar",
	"(GMT+08:00) Perth":                                 "Australia/Perth",
	"(GMT+08:30) Pyongyang":                             "Asia/Pyongyang",
	"(GMT+08:30) Eucla":                                 "Australia/Eucla",
	"(GMT+09:00) Chita":                                 "Asia/Chita",
	"(GMT+09:00) Dili":                                  "Asia/Dili",
	"(GMT+09:00) Jayapura":                              "Asia/Jayapura",
	"(GMT+09:00) Khandyga":                              "Asia/Khandyga",
	"(GMT+09:00) Osaka, Sapporo, Tokyo":                 "Asia/Tokyo",
	"(GMT+09:00) Seoul":                                 "Asia/Seoul",
	"(GMT+09:00) Yakutsk":                               "Asia/Yakutsk",
	"(GMT+09:00) Palau":                                 "Pacific/Palau",
	"(GMT+09:30) Adelaide":                              "Australia/Adelaide",
	"(GMT+09:30) Broken Hill":                           "Australia/Broken_Hill",
	"(GMT+09:30) Darwin":                                "Australia/Darwin",
	"(GMT+10:00) Brisbane":                              "Australia/Brisbane",
	"(GMT+10:00) Vladivostok":                           "Asia/Vladivostok",
	"(GMT+10:00) Hobart":                                "Australia/Hobart",
	"(GMT+10:00) Lindeman":                              "Australia/Lindeman",
	"(GMT+10:00) Chuuk":                                 "Pacific/Chuuk",
	"(GMT+10:00) Saipan":                                "Pacific/Saipan",
	"(GMT+10:00) Guam, Port Moresby":                    "Pacific/Port_Moresby",
	"(GMT+10:30) Lord Howe Island":                      "Australia/Lord_Howe",
	"(GMT+11:00) Sakhalin":                              "Asia/Sakhalin",
	"(GMT+11:00) Srednekolymsk":                         "Asia/Srednekolymsk",
	"(GMT+11:00) Magadan, Solomon Is., New Caledonia":   "Asia/Magadan",
	"(GMT+11:00) Currie":                                "Australia/Currie",
	"(GMT+11:00) Melbourne":                             "Australia/Melbourne",
	"(GMT+11:00) Sydney":                                "Australia/Sydney",
	"(GMT+11:00) Efate":                                 "Pacific/Efate",
	"(GMT+11:00) Bougainville":                          "Pacific/Bougainville",
	"(GMT+11:00) Guadalcanal":                           "Pacific/Guadalcanal",
	"(GMT+11:00) Kosrae":                                "Pacific/Kosrae",
	"(GMT+11:00) Norfolk":                               "Pacific/Norfolk",
	"(GMT+11:00) Noumea":                                "Pacific/Noumea",
	"(GMT+11:00) Pohnpei":                               "Pacific/Pohnpei",
	"(GMT+12:00) Anadyr":                                "Asia/Anadyr",
	"(GMT+12:00) Petropavlovsk-Kamchatsky":              "Asia/Kamchatka",
	"(GMT+12:00) Coordinated Universal Time+12":         "Etc/GMT-12",
	"(GMT+12:00) Funafuti":                              "Pacific/Funafuti",
	"(GMT+12:00) Kwajalein":                             "Pacific/Kwajalein",
	"(GMT+12:00) Majuro":                                "Pacific/Majuro",
	"(GMT+12:00) Nauru":                                 "Pacific/Nauru",
	"(GMT+12:00) Tarawa":                                "Pacific/Tarawa",
	"(GMT+12:00) Wake":                                  "Pacific/Wake",
	"(GMT+12:00) Wallis":                                "Pacific/Wallis",
	"(GMT+12:00) Auckland, Wellington":                  "Pacific/Auckland",
	"(GMT+12:00) Fiji":                                  "Pacific/Fiji",
	"(GMT+12:45) Chatham Islands":                       "Pacific/Chatham",
	"(GMT+13:00) Phoenix Islands, Tokelau, Tonga":       "Pacific/Enderbury",
	"(GMT+13:00) Fakaofo":                               "Pacific/Fakaofo",
	"(GMT+13:00) Tongatapu":                             "Pacific/Tongatapu",
	"(GMT+14:00) Apia":                                  "Pacific/Apia",
	"(GMT+14:00) Line Islands":                          "Pacific/Kiritimati",
}

var ianaToWindowsMap = map[string]string{
	"Etc/GMT+12":             "UTC-12:00",
	"Etc/GMT+11":             "UTC-11:00",
	"Pacific/Midway":         "UTC-11:00",
	"Pacific/Niue":           "UTC-11:00",
	"Pacific/Pago_Pago":      "UTC-11:00",
	"Pacific/Samoa":          "Samoa Standard Time",
	"America/Adak":           "Hawaiian Standard Time",
	"Pacific/Rarotonga":      "Hawaiian Standard Time",
	"Pacific/Tahiti":         "Hawaiian Standard Time",
	"Pacific/Honolulu":       "Hawaiian Standard Time",
	"Pacific/Marquesas":      "Marquesas Standard Time",
	"America/Anchorage":      "Alaskan Standard Time",
	"Pacific/Gambier":        "UTC-09:00",
	"America/Juneau":         "Alaskan Standard Time",
	"America/Nome":           "Alaskan Standard Time",
	"America/Metlakatla":     "Alaskan Standard Time",
	"America/Sitka":          "Alaskan Standard Time",
	"America/Yakutat":        "Alaskan Standard Time",
	"America/Tijuana":        "Pacific Standard Time (Mexico)",
	"America/Los_Angeles":    "Pacific Standard Time",
	"Pacific/Pitcairn":       "Pacific Standard Time",
	"America/Creston":        "US Mountain Standard Time",
	"America/Chihuahua":      "Mountain Standard Time (Mexico)",
	"America/Dawson":         "Mountain Standard Time",
	"America/Dawson_Creek":   "US Mountain Standard Time",
	"America/Denver":         "Mountain Standard Time",
	"America/Ensenada":       "Pacific Standard Time (Mexico)",
	"America/Fort_Nelson":    "US Mountain Standard Time",
	"America/Hermosillo":     "US Mountain Standard Time",
	"America/Vancouver":      "Pacific Standard Time",
	"America/Whitehorse":     "Mountain Standard Time",
	"America/Phoenix":        "US Mountain Standard Time",
	"America/Bahia_Banderas": "Central Standard Time (Mexico)",
	"America/Belize":         "Central America Standard Time",
	"America/Boise":          "Mountain Standard Time",
	"America/Costa_Rica":     "Central America Standard Time",
	"America/Chicago":        "Central Standard Time",
	"America/Edmonton":       "Mountain Standard Time",
	"America/El_Salvador":    "Central America Standard Time",
	"America/Guatemala":      "Central America Standard Time",
	"America/Managua":        "Central America Standard Time",
	"America/Mazatlan":       "Mountain Standard Time (Mexico)",
	"America/Ojinaga":        "Mountain Standard Time (Mexico)",
	"America/Swift_Current":  "Central Standard Time",
	"America/Tegucigalpa":    "Central America Standard Time",
	"America/Mexico_City":    "Central Standard Time (Mexico)",
	"America/Regina":         "Central Standard Time",
	"Pacific/Galapagos":      "Central America Standard Time",
	"America/Atikokan":       "Eastern Standard Time",
	"America/Bogota":         "SA Pacific Standard Time",
	"America/Cancun":         "Eastern Standard Time (Mexico)",
	"America/Cayman":         "SA Pacific Standard Time",
	"America/Coral_Harbour":  "Eastern Standard Time",
	"America/Eirunepe":       "SA Pacific Standard Time",
	"America/Guayaquil":      "SA Pacific Standard Time",
	"America/Indianapolis":   "US Eastern Standard Time",
	"America/Jamaica":        "SA Pacific Standard Time",
	"America/Lima":           "SA Pacific Standard Time",
	"America/Matamoros":      "Central Standard Time",
	"America/Menominee":      "Central Standard Time",
	"America/Merida":         "Central Standard Time (Mexico)",
	"America/Monterrey":      "Central Standard Time (Mexico)",
	"America/Nipigon":        "Eastern Standard Time",
	"America/Panama":         "SA Pacific Standard Time",
	"America/Rainy_River":    "Central Standard Time",
	"America/Rio_Branco":     "SA Pacific Standard Time",
	"America/Thunder_Bay":    "Eastern Standard Time",
	"America/Winnipeg":       "Central Standard Time",
	"America/New_York":       "Eastern Standard Time",
	"Pacific/Easter":         "Easter Island Standard Time",
	"America/Caracas":        "Venezuela Standard Time",
	"America/Anguilla":       "Atlantic Standard Time",
	"America/Antigua":        "Atlantic Standard Time",
	"America/Aruba":          "Atlantic Standard Time",
	"America/Asuncion":       "Paraguay Standard Time",
	"America/Barbados":       "Atlantic Standard Time",
	"America/Boa_Vista":      "SA Western Standard Time",
	"America/Campo_Grande":   "Central Brazilian Standard Time",
	"America/Curacao":        "Atlantic Standard Time",
	"America/Cuiaba":         "Central Brazilian Standard Time",
	"America/Detroit":        "Eastern Standard Time",
	"America/Dominica":       "Atlantic Standard Time",
	"America/Grand_Turk":     "Turks And Caicos Standard Time",
	"America/Grenada":        "Atlantic Standard Time",
	"America/Guadeloupe":     "Atlantic Standard Time",
	"America/Guyana":         "SA Western Standard Time",
	"America/Halifax":        "Atlantic Standard Time",
	"America/Havana":         "Cuba Standard Time",
	"America/La_Paz":         "SA Western Standard Time",
	"America/Manaus":         "SA Western Standard Time",
	"America/Martinique":     "Atlantic Standard Time",
	"America/Montreal":       "Eastern Standard Time",
	"America/Montserrat":     "Atlantic Standard Time",
	"America/Nassau":         "Eastern Standard Time",
	"America/Port_of_Spain":  "Atlantic Standard Time",
	"America/Porto_Velho":    "SA Western Standard Time",
	"America/Puerto_Rico":    "Atlantic Standard Time",
	"America/Santo_Domingo":  "Atlantic Standard Time",
	"America/St_Kitts":       "Atlantic Standard Time",
	"America/St_Lucia":       "Atlantic Standard Time",
	"America/St_Thomas":      "Atlantic Standard Time",
	"America/St_Vincent":     "Atlantic Standard Time",
	"America/Toronto":        "Eastern Standard Time",
	"America/Tortola":        "Atlantic Standard Time",
	"America/Santiago":       "Pacific SA Standard Time",
	"America/St_Johns":       "Newfoundland Standard Time",
	"America/Araguaina":      "Tocantins Standard Time",
	"America/Bahia":          "Bahia Standard Time",
	"America/Belem":          "SA Eastern Standard Time",
	"America/Buenos_Aires":   "Argentina Standard Time",
	"America/Cayenne":        "SA Eastern Standard Time",
	"America/Fortaleza":      "SA Eastern Standard Time",
	"America/Glace_Bay":      "Atlantic Standard Time",
	"America/Goose_Bay":      "Atlantic Standard Time",
	"America/Godthab":        "Greenland Standard Time",
	"America/Maceio":         "SA Eastern Standard Time",
	"America/Moncton":        "Atlantic Standard Time",
	"America/Paramaribo":     "SA Eastern Standard Time",
	"America/Punta_Arenas":   "Magallanes Standard Time",
	"America/Recife":         "SA Eastern Standard Time",
	"America/Rosario":        "Argentina Standard Time",
	"America/Santarem":       "SA Eastern Standard Time",
	"America/Thule":          "Atlantic Standard Time",
	"America/Montevideo":     "Montevideo Standard Time",
	"America/Sao_Paulo":      "E. South America Standard Time",
	"Antarctica/Rothera":     "SA Eastern Standard Time",
	"Atlantic/Bermuda":       "Atlantic Standard Time",
	"Atlantic/Stanley":       "Falkland Islands Standard Time",
	"America/Miquelon":       "Saint Pierre Standard Time",
	"America/Noronha":        "UTC-02:00",
	"Atlantic/South_Georgia": "South Georgia Standard Time",
	"Etc/GMT+2":              "UTC-02:00",
	"Atlantic/Azores":        "Azores Standard Time",
	"Atlantic/Cape_Verde":    "Cape Verde Standard Time",
	"UTC":                    "Coordinated Universal Time",
	"America/Danmarkshavn":   "UTC",
	"America/Scoresbysund":   "Greenland Standard Time",
	"Africa/Accra":           "Greenwich Standard Time",
	"Africa/Abidjan":         "Greenwich Standard Time",
	"Africa/Bamako":          "Greenwich Standard Time",
	"Africa/Banjul":          "Greenwich Standard Time",
	"Africa/Bissau":          "Greenwich Standard Time",
	"Africa/Conakry":         "Greenwich Standard Time",
	"Africa/Dakar":           "Greenwich Standard Time",
	"Africa/El_Aaiun":        "Greenwich Standard Time",
	"Africa/Freetown":        "Greenwich Standard Time",
	"Africa/Lome":            "Greenwich Standard Time",
	"Africa/Monrovia":        "Greenwich Standard Time",
	"Africa/Nouakchott":      "Greenwich Standard Time",
	"Africa/Ouagadougou":     "Greenwich Standard Time",
	"Africa/Sao_Tome":        "Greenwich Standard Time",
	"Africa/Timbuktu":        "Greenwich Standard Time",
	"Antarctica/Troll":       "Greenwich Standard Time",
	"Atlantic/St_Helena":     "Greenwich Standard Time",
	"Atlantic/Reykjavik":     "Greenwich Standard Time",
	"Europe/London":          "GMT Standard Time",
	"Africa/Bangui":          "W. Central Africa Standard Time",
	"Africa/Casablanca":      "Morocco Standard Time",
	"Africa/Algiers":         "Central European Standard Time",
	"Africa/Brazzaville":     "W. Central Africa Standard Time",
	"Africa/Douala":          "W. Central Africa Standard Time",
	"Africa/Kinshasa":        "W. Central Africa Standard Time",
	"Africa/Libreville":      "W. Central Africa Standard Time",
	"Africa/Luanda":          "W. Central Africa Standard Time",
	"Africa/Malabo":          "W. Central Africa Standard Time",
	"Africa/Ndjamena":        "W. Central Africa Standard Time",
	"Africa/Niamey":          "W. Central Africa Standard Time",
	"Africa/Tunis":           "Central European Standard Time",
	"Africa/Lagos":           "W. Central Africa Standard Time",
	"Atlantic/Canary":        "GMT Standard Time",
	"Atlantic/Faroe":         "GMT Standard Time",
	"Atlantic/Madeira":       "GMT Standard Time",
	"Europe/Belfast":         "GMT Standard Time",
	"Europe/Berlin":          "W. Europe Standard Time",
	"Europe/Budapest":        "Central Europe Standard Time",
	"Europe/Dublin":          "GMT Standard Time",
	"Europe/Guernsey":        "GMT Standard Time",
	"Europe/Isle_of_Man":     "GMT Standard Time",
	"Europe/Jersey":          "GMT Standard Time",
	"Europe/Lisbon":          "GMT Standard Time",
	"Europe/Paris":           "Romance Standard Time",
	"Europe/Warsaw":          "Central European Standard Time",
	"Africa/Blantyre":        "South Africa Standard Time",
	"Africa/Bujumbura":       "South Africa Standard Time",
	"Africa/Cairo":           "Egypt Standard Time",
	"Africa/Ceuta":           "Romance Standard Time",
	"Africa/Johannesburg":    "South Africa Standard Time",
	"Africa/Gaborone":        "South Africa Standard Time",
	"Africa/Harare":          "South Africa Standard Time",
	"Africa/Khartoum":        "Sudan Standard Time",
	"Africa/Kigali":          "South Africa Standard Time",
	"Africa/Lubumbashi":      "South Africa Standard Time",
	"Africa/Lusaka":          "South Africa Standard Time",
	"Africa/Maputo":          "South Africa Standard Time",
	"Africa/Maseru":          "South Africa Standard Time",
	"Africa/Mbabane":         "South Africa Standard Time",
	"Africa/Tripoli":         "Libya Standard Time",
	"Africa/Windhoek":        "Namibia Standard Time",
	"Asia/Amman":             "Jordan Standard Time",
	"Asia/Beirut":            "Middle East Standard Time",
	"Asia/Damascus":          "Syria Standard Time",
	"Asia/Jerusalem":         "Israel Standard Time",
	"Europe/Amsterdam":       "W. Europe Standard Time",
	"Europe/Andorra":         "W. Europe Standard Time",
	"Europe/Belgrade":        "Central Europe Standard Time",
	"Europe/Brussels":        "Romance Standard Time",
	"Europe/Copenhagen":      "Romance Standard Time",
	"Europe/Gibraltar":       "W. Europe Standard Time",
	"Europe/Istanbul":        "Turkey Standard Time",
	"Europe/Kaliningrad":     "Kaliningrad Standard Time",
	"Europe/Kiev":            "FLE Standard Time",
	"Europe/Ljubljana":       "Central Europe Standard Time",
	"Europe/Luxembourg":      "W. Europe Standard Time",
	"Europe/Madrid":          "Romance Standard Time",
	"Europe/Malta":           "W. Europe Standard Time",
	"Europe/Monaco":          "W. Europe Standard Time",
	"Europe/Minsk":           "Belarus Standard Time",
	"Europe/Oslo":            "W. Europe Standard Time",
	"Europe/Prague":          "Central Europe Standard Time",
	"Europe/Rome":            "W. Europe Standard Time",
	"Europe/Sarajevo":        "Central Europe Standard Time",
	"Europe/Skopje":          "Central Europe Standard Time",
	"Europe/Stockholm":       "W. Europe Standard Time",
	"Europe/Tirane":          "Central Europe Standard Time",
	"Europe/Vaduz":           "W. Europe Standard Time",
	"Europe/Vienna":          "W. Europe Standard Time",
	"Europe/Zagreb":          "Central Europe Standard Time",
	"Europe/Zurich":          "W. Europe Standard Time",
	"Africa/Addis_Ababa":     "E. Africa Standard Time",
	"Africa/Asmara":          "E. Africa Standard Time",
	"Africa/Dar_es_Salaam":   "E. Africa Standard Time",
	"Africa/Djibouti":        "E. Africa Standard Time",
	"Africa/Juba":            "E. Africa Standard Time",
	"Africa/Kampala":         "E. Africa Standard Time",
	"Africa/Mogadishu":       "E. Africa Standard Time",
	"Africa/Nairobi":         "E. Africa Standard Time",
	"Asia/Aden":              "Arab Standard Time",
	"Asia/Bahrain":           "Arab Standard Time",
	"Asia/Baghdad":           "Arabic Standard Time",
	"Asia/Famagusta":         "Turkey Standard Time",
	"Asia/Gaza":              "Middle East Standard Time",
	"Asia/Hebron":            "Middle East Standard Time",
	"Asia/Kuwait":            "Arab Standard Time",
	"Asia/Nicosia":           "E. Europe Standard Time",
	"Asia/Qatar":             "Arab Standard Time",
	"Asia/Tel_Aviv":          "Israel Standard Time",
	"Asia/Riyadh":            "Arab Standard Time",
	"Europe/Athens":          "GTB Standard Time",
	"Europe/Bucharest":       "GTB Standard Time",
	"Europe/Chisinau":        "E. Europe Standard Time",
	"Europe/Helsinki":        "FLE Standard Time",
	"Europe/Kirov":           "Russian Standard Time",
	"Europe/Moscow":          "Russian Standard Time",
	"Europe/Riga":            "FLE Standard Time",
	"Europe/Simferopol":      "Russian Standard Time",
	"Europe/Sofia":           "FLE Standard Time",
	"Europe/Tallinn":         "FLE Standard Time",
	"Europe/Tiraspol":        "E. Europe Standard Time",
	"Europe/Uzhgorod":        "FLE Standard Time",
	"Europe/Vilnius":         "FLE Standard Time",
	"Europe/Volgograd":       "Russian Standard Time",
	"Europe/Zaporozhye":      "FLE Standard Time",
	"Indian/Antananarivo":    "E. Africa Standard Time",
	"Indian/Comoro":          "E. Africa Standard Time",
	"Indian/Mayotte":         "E. Africa Standard Time",
	"Asia/Tehran":            "Iran Standard Time",
	"Asia/Baku":              "Azerbaijan Standard Time",
	"Asia/Muscat":            "Arabian Standard Time",
	"Asia/Dubai":             "Arabian Standard Time",
	"Asia/Tbilisi":           "Georgian Standard Time",
	"Asia/Yerevan":           "Caucasus Standard Time",
	"Europe/Astrakhan":       "Russian Standard Time",
	"Europe/Samara":          "Russia Time Zone 3",
	"Europe/Saratov":         "Russian Standard Time",
	"Europe/Ulyanovsk":       "Russian Standard Time",
	"Indian/Mahe":            "Mauritius Standard Time",
	"Indian/Mauritius":       "Mauritius Standard Time",
	"Indian/Reunion":         "Mauritius Standard Time",
	"Asia/Kabul":             "Afghanistan Standard Time",
	"Antarctica/Mawson":      "West Asia Standard Time",
	"Asia/Aqtau":             "West Asia Standard Time",
	"Asia/Aqtobe":            "West Asia Standard Time",
	"Asia/Ashgabat":          "West Asia Standard Time",
	"Asia/Atyrau":            "West Asia Standard Time",
	"Asia/Dushanbe":          "West Asia Standard Time",
	"Asia/Oral":              "West Asia Standard Time",
	"Asia/Samarkand":         "West Asia Standard Time",
	"Asia/Karachi":           "Pakistan Standard Time",
	"Asia/Tashkent":          "West Asia Standard Time",
	"Asia/Yekaterinburg":     "Ekaterinburg Standard Time",
	"Indian/Maldives":        "West Asia Standard Time",
	"Asia/Calcutta":          "India Standard Time",
	"Asia/Colombo":           "Sri Lanka Standard Time",
	"Asia/Kolkata":           "India Standard Time",
	"Asia/Kathmandu":         "Nepal Standard Time",
	"Asia/Almaty":            "Central Asia Standard Time",
	"Asia/Bishkek":           "Central Asia Standard Time",
	"Asia/Kashgar":           "Central Asia Standard Time",
	"Asia/Omsk":              "Omsk Standard Time",
	"Asia/Qyzylorda":         "Central Asia Standard Time",
	"Asia/Thimphu":           "Central Asia Standard Time",
	"Asia/Urumqi":            "Central Asia Standard Time",
	"Asia/Dhaka":             "Bangladesh Standard Time",
	"Asia/Novosibirsk":       "N. Central Asia Standard Time",
	"Indian/Chagos":          "Central Asia Standard Time",
	"Asia/Yangon":            "Myanmar Standard Time",
	"Asia/Rangoon":           "Myanmar Standard Time",
	"Indian/Cocos":           "Myanmar Standard Time",
	"Antarctica/Davis":       "SE Asia Standard Time",
	"Asia/Barnaul":           "North Asia Standard Time",
	"Asia/Bangkok":           "SE Asia Standard Time",
	"Asia/Ho_Chi_Minh":       "SE Asia Standard Time",
	"Asia/Hovd":              "W. Mongolia Standard Time",
	"Asia/Jakarta":           "SE Asia Standard Time",
	"Asia/Novokuznetsk":      "North Asia Standard Time",
	"Asia/Phnom_Penh":        "SE Asia Standard Time",
	"Asia/Pontianak":         "SE Asia Standard Time",
	"Asia/Tomsk":             "North Asia Standard Time",
	"Asia/Vientiane":         "SE Asia Standard Time",
	"Asia/Krasnoyarsk":       "North Asia Standard Time",
	"Indian/Christmas":       "SE Asia Standard Time",
	"Antarctica/Casey":       "W. Australia Standard Time",
	"Asia/Brunei":            "Singapore Standard Time",
	"Asia/Choibalsan":        "Ulaanbaatar Standard Time",
	"Asia/Chongqing":         "China Standard Time",
	"Asia/Harbin":            "China Standard Time",
	"Asia/Hong_Kong":         "Hong Kong Standard Time",
	"Asia/Kuala_Lumpur":      "Singapore Standard Time",
	"Asia/Kuching":           "Singapore Standard Time",
	"Asia/Macau":             "China Standard Time",
	"Asia/Makassar":          "Singapore Standard Time",
	"Asia/Manila":            "Singapore Standard Time",
	"Asia/Irkutsk":           "North Asia East Standard Time",
	"Asia/Shanghai":          "China Standard Time",
	"Asia/Singapore":         "Singapore Standard Time",
	"Asia/Taipei":            "Taipei Standard Time",
	"Asia/Ulaanbaatar":       "Ulaanbaatar Standard Time",
	"Australia/Perth":        "W. Australia Standard Time",
	"Asia/Pyongyang":         "Korean Standard Time",
	"Australia/Eucla":        "Aus Central W. Standard Time",
	"Asia/Chita":             "Yakutsk Standard Time",
	"Asia/Dili":              "Tokyo Standard Time",
	"Asia/Jayapura":          "Tokyo Standard Time",
	"Asia/Khandyga":          "Yakutsk Standard Time",
	"Asia/Tokyo":             "Tokyo Standard Time",
	"Asia/Seoul":             "Korean Standard Time",
	"Asia/Yakutsk":           "Yakutsk Standard Time",
	"Pacific/Palau":          "Tokyo Standard Time",
	"Australia/Adelaide":     "Cen. Australia Standard Time",
	"Australia/Broken_Hill":  "Cen. Australia Standard Time",
	"Australia/Darwin":       "AUS Central Standard Time",
	"Australia/Brisbane":     "E. Australia Standard Time",
	"Asia/Vladivostok":       "Vladivostok Standard Time",
	"Australia/Hobart":       "Tasmania Standard Time",
	"Australia/Lindeman":     "E. Australia Standard Time",
	"Pacific/Chuuk":          "West Pacific Standard Time",
	"Pacific/Saipan":         "West Pacific Standard Time",
	"Pacific/Port_Moresby":   "West Pacific Standard Time",
	"Australia/Lord_Howe":    "Lord Howe Standard Time",
	"Asia/Sakhalin":          "Sakhalin Standard Time",
	"Asia/Srednekolymsk":     "Russia Time Zone 10",
	"Asia/Magadan":           "Magadan Standard Time",
	"Australia/Currie":       "Tasmania Standard Time",
	"Australia/Melbourne":    "AUS Eastern Standard Time",
	"Australia/Sydney":       "AUS Eastern Standard Time",
	"Pacific/Efate":          "Central Pacific Standard Time",
	"Pacific/Bougainville":   "Central Pacific Standard Time",
	"Pacific/Guadalcanal":    "Central Pacific Standard Time",
	"Pacific/Kosrae":         "Central Pacific Standard Time",
	"Pacific/Norfolk":        "Norfolk Standard Time",
	"Pacific/Noumea":         "Central Pacific Standard Time",
	"Pacific/Pohnpei":        "Central Pacific Standard Time",
	"Asia/Anadyr":            "Russia Time Zone 11",
	"Asia/Kamchatka":         "Russia Time Zone 11",
	"Etc/GMT-12":             "UTC+12:00",
	"Pacific/Funafuti":       "UTC+12:00",
	"Pacific/Kwajalein":      "UTC+12:00",
	"Pacific/Majuro":         "UTC+12:00",
	"Pacific/Nauru":          "UTC+12:00",
	"Pacific/Tarawa":         "UTC+12:00",
	"Pacific/Wake":           "UTC+12:00",
	"Pacific/Wallis":         "UTC+12:00",
	"Pacific/Auckland":       "New Zealand Standard Time",
	"Pacific/Fiji":           "Fiji Standard Time",
	"Pacific/Chatham":        "Chatham Islands Standard Time",
	"Pacific/Enderbury":      "UTC+13:00",
	"Pacific/Fakaofo":        "UTC+13:00",
	"Pacific/Tongatapu":      "Tonga Standard Time",
	"Pacific/Apia":           "Samoa Standard Time",
	"Pacific/Kiritimati":     "Line Islands Standard Time",
}
