// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FindTimezone(arg1:string):Promise<Array<main.TzResponse>>;

export function Greet(arg1:string):Promise<string>;
